baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Marvin L.C. Hoffman'
theme = 'ananke'

[pagination]
    disableAliases = false
    pagerSize = 2
    path = 'page'

[params]
    subtitle = "A good story is a dream shared by the author and the reader. Anything that wakes the reader from the dream is a mortal sin."
    quotecredit = 'Victor J. Banis'
    #description = 'a description'
    [params.contact]
        email = 'marvin@marvinlchoffman.com'


sectionPagesMenu = 'main'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Portfolio'
    pageRef = '/portfolio'
    weight = 30
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 40
