baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Marvin LC Hoffman'
subtitle = 'cool quote goes here'
theme = 'ananke'

[pagination]
    disableAliases = false
    pagerSize = 2
    path = 'page'

[params]
    subtitle = 'cool author quote'
    description = 'a description'
    [params.contact]
        email = 'marvin@marvinlchoffman.com'


sectionPagesMenu = 'main'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Portfolio'
    pageRef = '/portfolio'
    weight = 30
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 40
